INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('East Central College', '1', 'ECC Staff');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('East Central College', '2', 'ECC Faculty');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('East Central College', '3', 'ECC Student');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('East Central College', '4', 'ECC Community');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Mineral Area College', '31', 'MAC Student');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Mineral Area College', '32', 'MAC Faculty/Staff');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Mineral Area College', '33', 'MAC Adjunct');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Mineral Area College', '34', 'MAC Upward Bound');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Mineral Area College', '35', 'MAC Talent Search');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Mineral Area College', '36', 'MAC Community Borrowers');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Jefferson College', '51', 'JC Student');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Jefferson College', '52', 'JC Faculty/Staff');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Jefferson College', '53', 'JC Adjunct');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Jefferson College', '55', 'JC Community');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Jefferson College', '56', 'JC AEL');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Jefferson College', '57', 'JC ILL');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Three Rivers College', '61', 'TRC Student');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Three Rivers College', '62', 'TRC Faculty/Staff');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Three Rivers College', '63', 'TRC Non-Student');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Three Rivers College', '65', 'TRC ILL');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('St Charles Community College', '101', 'SCC Student');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('St Charles Community College', '102', 'SCC Faculty/Staff');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('St Charles Community College', '103', 'SCC Alumni');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('St Charles Community College', '104', 'SCC Community Users');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('St Charles Community College', '105', 'SCC ILL');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('St Charles Community College', '106', 'None');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('St Charles Community College', '107', 'None');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('St Charles Community College', '108', 'SCC Board of Trustees');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('St Charles Community College', '109', 'None');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('St Charles Community College', '110', 'None');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('St. Louis Community College', '151', 'STLCC Student');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('St. Louis Community College', '152', 'STLCC Alumni');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('St. Louis Community College', '153', 'STLCC Courtesy');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('St. Louis Community College', '154', 'STLCC Staff');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('St. Louis Community College', '155', 'STLCC Emeritus');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('St. Louis Community College', '156', 'STLCC ILL');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('St. Louis Community College', '157', 'STLCC Department');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('University of Health Sciences and Pharmacy', '180', 'UHSP Student');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('University of Health Sciences and Pharmacy', '181', 'UHSP Faculty');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('University of Health Sciences and Pharmacy', '182', 'UHSP Staff');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('University of Health Sciences and Pharmacy', '183', 'UHSP Alumni');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('University of Health Sciences and Pharmacy', '184', 'UHSP Preceptor');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('University of Health Sciences and Pharmacy', '185', 'UHSP ILL');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('University of Health Sciences and Pharmacy', '186', 'UHSP Other');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Lincoln University', '1', 'LINC Undergraduate Student');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Lincoln University', '2', 'LINC Staff/Graduates');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Lincoln University', '3', 'LINC Faculty/Staff');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Lincoln University', '4', 'LINC Community');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Lincoln University', '7', 'LINC ILL');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Lincoln University', '8', 'None');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Lincoln University', '10', 'LINC Faculty/Board/Emeritus');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Lincoln University', '11', 'None');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Columbia College', '51', 'None');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Columbia College', '52', 'CCIS Students');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Columbia College', '53', 'None');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Columbia College', '54', 'CCIS Faculty/Staff');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Columbia College', '55', 'CCIS Board/Emeritus');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Columbia College', '56', 'None');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Columbia College', '57', 'CCIS ILL');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Columbia College', '58', 'CCIS Courtesy');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Columbia College', '59', 'None');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Columbia College', '60', 'None');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Columbia College', '61', 'None');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Columbia College', '62', 'None');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Columbia College', '63', 'None');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Columbia College', '64', 'None');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Missouri State Library', '80', 'MOSL State Employee');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Missouri State Library', '81', 'MOSL Restricted State Employee');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Missouri State Library', '83', 'MOSL State Intern');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Missouri State Library', '84', 'MOSL Missouri Resident');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Missouri State Library', '85', 'MOSL Missouri Library');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Missouri State Library', '86', 'MOSL Public Library Director');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Missouri State Library', '87', 'MOSL ILL Lending');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Stephens College', '101', 'SC STEPHENS Undergraduate Student');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Stephens College', '102', 'SC STEPHENS Graduate Student');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Stephens College', '103', 'SC STEPHENS Faculty/Staff/Retiree');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Stephens College', '108', 'SC STEPHENS Children''s School');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Stephens College', '111', 'SC STEPHENS ILL');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Stephens College', '112', 'SC STEPHENS Guest');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Westminster College', '151', 'WC Undergraduate');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Westminster College', '153', 'WC Faculty');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Westminster College', '154', 'WC Staff');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Westminster College', '156', 'WC Resident');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Westminster College', '159', 'WC ILL');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('William Woods University', '181', 'WWU Undergraduate');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('William Woods University', '182', 'WWU Graduate');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('William Woods University', '183', 'WWU Faculty/Staff');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('William Woods University', '184', 'WWU Community Guest');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('William Woods University', '185', 'WWU ILL');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('William Woods University', '186', 'WWU Adjunct Faculty');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('William Woods University', '187', 'WWU Adult Studies');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Culver-Stockton College', '1', 'CSC Student');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Culver-Stockton College', '2', 'CSC Employee');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Culver-Stockton College', '3', 'None');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Culver-Stockton College', '4', 'CSC ILL');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Culver-Stockton College', '5', 'CSC Community Borrower');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Culver-Stockton College', '6', 'None');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Central Methodist University', '7', 'None');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Central Methodist University', '8', 'CMU Extended Student');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Central Methodist University', '10', 'CMU Student');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Central Methodist University', '11', 'CMU Staff');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Central Methodist University', '12', 'CMU Faculty');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Central Methodist University', '14', 'CMU Guest');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Missouri Valley College', '15', 'CMU Grad/Honors');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Missouri Valley College', '30', 'MVC Student');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Missouri Valley College', '31', 'MVC Faulty/Staff');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Missouri Valley College', '32', 'MVC ILL');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Missouri Valley College', '33', 'MVC Public');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Missouri Valley College', '34', 'None');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('State Fair Community College', '35', 'MVC Graduate');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('State Fair Community College', '40', 'SFCC Student');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('State Fair Community College', '41', 'SFCC Faculty/Staff');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('State Fair Community College', '42', 'SFCC ILL');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('State Fair Community College', '43', 'SFCC Community');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('A.T. Still University', '51', 'ATSU Student');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('A.T. Still University', '52', 'ATSU Faculty');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('A.T. Still University', '53', 'ATSU Staff');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('A.T. Still University', '54', 'ATSU Hospital Staff');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('A.T. Still University', '55', 'ATSU Community Borrower');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('A.T. Still University', '56', 'ATSU Binding');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('A.T. Still University', '57', 'ATSU ILL');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('A.T. Still University', '58', 'ATSU ILL Arizona');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('State Technical College', '59', 'ATSU Library Staff');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('State Technical College', '61', 'STC STCC Student');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('State Technical College', '62', 'STC STCC Staff');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('State Technical College', '63', 'STC STCC Faculty');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('State Technical College', '64', 'STC STCC Administration');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('State Technical College', '65', 'STC STCC Board');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('State Technical College', '66', 'STC STCC Alumni');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('State Technical College', '67', 'STC STCC Community');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('State Technical College', '68', 'None');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('State Technical College', '69', 'None');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('State Technical College', '70', 'None');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Moberly Area Community College', '71', 'None');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Moberly Area Community College', '81', 'MACC Student');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Moberly Area Community College', '82', 'MACC Faculty/Staff/Board Member');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Moberly Area Community College', '83', 'MACC Community Borrower');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Moberly Area Community College', '84', 'None');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Hannibal-LaGrange University', '91', 'HLGU Student');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Hannibal-LaGrange University', '92', 'HLGU Faculty/Staff');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Hannibal-LaGrange University', '93', 'HLGU ILL');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Hannibal-LaGrange University', '94', 'HLGU Community Borrower');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Hannibal-LaGrange University', '95', 'HLGU Affiliate');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Hannibal-LaGrange University', '96', 'None');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Truman State University', '101', 'TRUMAN Community Borrower');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Truman State University', '102', 'TRUMAN Academy');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Truman State University', '103', 'TRUMAN Undergraduate');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Truman State University', '104', 'TRUMAN Graduate');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Truman State University', '105', 'TRUMAN Designated Guest');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Truman State University', '106', 'TRUMAN Staff');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Truman State University', '107', 'TRUMAN Faculty');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Truman State University', '108', 'TRUMAN Library in House');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Truman State University', '109', 'None');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Truman State University', '110', 'None');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Truman State University', '111', 'None');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Truman State University', '112', 'None');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Covenant Theological Seminary', '0', 'COV Student (St. Louis)');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Covenant Theological Seminary', '1', 'COV Faculty');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Covenant Theological Seminary', '2', 'COV Community');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Covenant Theological Seminary', '3', 'COV Alumnus');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Covenant Theological Seminary', '5', 'COV ILL');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Covenant Theological Seminary', '6', 'COV Reciprocal Borrower');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Covenant Theological Seminary', '7', 'COV Student (Nashville)');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Covenant Theological Seminary', '8', 'COV Student (DMin)');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Covenant Theological Seminary', '9', 'COV Student (Online)');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Covenant Theological Seminary', '10', 'COV Library Staff');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Covenant Theological Seminary', '11', 'COV Staff');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Covenant Theological Seminary', '12', 'COV Student (Phoenix)');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Covenant Theological Seminary', '14', 'COV Minister');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Covenant Theological Seminary', '15', 'COV Church Member');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Covenant Theological Seminary', '19', 'COV Controlled Digital Lending');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Fontbonne University', '20', 'FONT Undergraduate Student');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Fontbonne University', '21', 'FONT Graduate Student');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Fontbonne University', '22', 'None');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Fontbonne University', '23', 'FONT Faculty/Staff');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Fontbonne University', '24', 'None');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Fontbonne University', '25', 'FONT Emeritus Faculty');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Fontbonne University', '26', 'FONT Alumni');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Fontbonne University', '27', 'FONT CSJ');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Fontbonne University', '28', 'FONT Courtesy');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Fontbonne University', '29', 'None');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Harris-Stowe State University', '30', 'FONT Info Pass');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Harris-Stowe State University', '40', 'HSSU Student');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Harris-Stowe State University', '41', 'HSSU Employee');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Harris-Stowe State University', '42', 'HSSU Courtesy');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Harris-Stowe State University', '43', 'HSSU Talent Search');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Kenrick-Glennon Seminary', '44', 'HSSU Upward Bound');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Kenrick-Glennon Seminary', '50', 'KGS Faculty/Staff');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Kenrick-Glennon Seminary', '51', 'KGS Student');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Kenrick-Glennon Seminary', '52', 'KGS Guest/Visitor');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Lindenwood University', '60', 'LIND LU Traditional Undergraduate');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Lindenwood University', '62', 'LIND LU Workshop Graduate, Off-Campus');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Lindenwood University', '64', 'LIND LU ADP Undergrad');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Lindenwood University', '65', 'LIND ADP Graduate');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Lindenwood University', '67', 'LIND LU Plaster College MBA');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Lindenwood University', '68', 'LIND LU Masters in Fine Arts');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Lindenwood University', '69', 'LIND LU Undergraduate Not on Campus');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Lindenwood University', '70', 'LIND LU Early College Start Student');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Lindenwood University', '71', 'LIND LU Specialist');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Lindenwood University', '72', 'LIND LU Masters');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Lindenwood University', '73', 'LIND LU Faculty (Full Time)');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Lindenwood University', '74', 'LIND LU Faculty Adjunct');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Lindenwood University', '75', 'LIND LU Staff');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Lindenwood University', '76', 'LIND LU Special (Board, Alumni, etc)');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Lindenwood University', '78', 'LIND LU ILL');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Lindenwood University', '80', 'LIND LU Doctoral');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Logan University', '90', 'LOGAN Adminstration');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Logan University', '91', 'LOGAN Alumni');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Logan University', '92', 'None');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Logan University', '93', 'LOGAN Faculty');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Logan University', '94', 'LOGAN Field Doctors');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Logan University', '95', 'LOGAN Info Pass');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Logan University', '96', 'LOGAN ILL');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Logan University', '97', 'None');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Logan University', '98', 'LOGAN Special Patron');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Logan University', '99', 'LOGAN Staff');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Logan University', '100', 'LOGAN Student');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Logan University', '101', 'None');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Maryville University', '110', 'None');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Maryville University', '111', 'MRYV Adjunct Faculty');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Maryville University', '112', 'MRYV Full Time Faculty');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Maryville University', '113', 'MRYV Part Time Faculty');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Maryville University', '114', 'None');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Maryville University', '115', 'MRYV Staff');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Maryville University', '116', 'MRYV Graduate Students');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Maryville University', '117', 'None');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Maryville University', '118', 'None');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Maryville University', '119', 'None');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Maryville University', '120', 'MRYV Undergraduate Students');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Maryville University', '121', 'MRYV Friends');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Maryville University', '122', 'MRYV Info Pass');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Maryville University', '123', 'None');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Maryville University', '124', 'None');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Maryville University', '125', 'None');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Maryville University', '126', 'None');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Maryville University', '127', 'None');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Maryville University', '128', 'None');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Maryville University', '129', 'MRYV St. Louis Women''s Chorale');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Missouri Baptist University', '140', 'MBU Students');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Missouri Baptist University', '141', 'MBU Faculty/Staff');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Missouri Baptist University', '142', 'MBU Friends of the Library');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Missouri Baptist University', '143', 'MBU ILL');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Missouri Baptist University', '144', 'MBU Doctoral');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Missouri Baptist University', '145', 'MBU Alumni');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Eden-Webster University', '151', 'EWL-Webster Students Online International');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Eden-Webster University', '152', 'EWL-Webster Students Online Domestic');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Eden-Webster University', '153', 'EWL-Webster Faculty International');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Eden-Webster University', '154', 'EWL-Webster Students International');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Eden-Webster University', '155', 'EWL-Webster Athens Undergraduate Students');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Eden-Webster University', '156', 'EWL-Webster Athens Graduate Students');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Eden-Webster University', '157', 'EWL-Webster Vienna Faculty/Staff');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Eden-Webster University', '158', 'EWL-Webster Vienna Students');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Eden-Webster University', '159', 'EWL-Webster Athens Faculty/Staff');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Eden-Webster University', '160', 'EWL-Eden Webster Staff');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Eden-Webster University', '161', 'EWL-Eden Faculty');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Eden-Webster University', '162', 'EWL-Webster Faculty');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Eden-Webster University', '163', 'EWL-Webster Faculty (MO)');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Eden-Webster University', '164', 'EWL-Webster Faculty (USA)');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Eden-Webster University', '165', 'EWL-Webster Students (USA)');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Eden-Webster University', '166', 'EWL-Webster Students (MO)');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Eden-Webster University', '167', 'EWL-Eden Students');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Eden-Webster University', '168', 'EWL-Webster Graduate Students');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Eden-Webster University', '169', 'EWL-Webster Undergraduate Students');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Eden-Webster University', '170', 'EWL-Webster Sites & Dual Admit Students');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Eden-Webster University', '171', 'EWL-Webster Dual Admit Fellows & Board of Trustees');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Eden-Webster University', '172', 'EWL-Eden Alumni');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Eden-Webster University', '173', 'EWL-Webster Alumni');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Eden-Webster University', '174', 'EWL-Eden Webster Other');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Eden-Webster University', '175', 'EWL-Eden Webster Infopass');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Eden-Webster University', '176', 'EWL-Eden Webster ILL');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Eden-Webster University', '177', 'EWL-Eden Webster Pseudo-Patrons');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Concordia Seminary', '180', 'CONC M.Div./M.Deac./Certificate');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Concordia Seminary', '181', 'CONC MA/STM/D.Min/Ph.D');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Concordia Seminary', '182', 'CONC Distance Program Student');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Concordia Seminary', '183', 'CONC Faculty');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Concordia Seminary', '184', 'CONC Staff');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Concordia Seminary', '185', 'CONC Guest Instructor');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Concordia Seminary', '186', 'CONC LCMS Rostered');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Concordia Seminary', '187', 'CONC ILL');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Concordia Seminary', '188', 'CONC Student Spouse');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Concordia Seminary', '189', 'CONC Emeriti');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Concordia Seminary', '190', 'CONC IC Researcher');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Concordia Seminary', '191', 'CONC CHI Staff');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Concordia Seminary', '192', 'CONC Non-Rostered Alumni');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Concordia Seminary', '194', 'CONC Special');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Missouri Botanical Garden', '0', 'MBG Institutional');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Missouri Botanical Garden', '1', 'MBG Intern');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Missouri Botanical Garden', '2', 'MBG Library Staff');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Missouri Botanical Garden', '3', 'MBG Special');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Missouri Botanical Garden', '4', 'MBG Staff');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Missouri Botanical Garden', '5', 'MBG Student');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Missouri Botanical Garden', '6', 'MBG Visitor');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('St. Louis Art Museum', '8', 'SLAM Library Staff');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('St. Louis Art Museum', '9', 'SLAM Museum Staff');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('St. Louis Art Museum', '10', 'SLAM ILL');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Missouri History Museum', '101', 'MHS Library Staff');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Missouri History Museum', '102', 'MHS Other Staff');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Missouri History Museum', '106', 'MHS ILL');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Missouri History Museum', '107', 'MHS Institutional');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Missouri History Museum', '110', 'MHS Condie');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Missouri History Museum', '111', 'MHS Former Staff');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Goldfarb School of Nursing', '150', 'GSN Student');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Goldfarb School of Nursing', '151', 'GSN Faculty');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Goldfarb School of Nursing', '152', 'GSN Staff');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Goldfarb School of Nursing', '153', 'GSN Alumni');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Goldfarb School of Nursing', '154', 'GSN Guest');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Avila University', '1', 'AU Student');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Avila University', '2', 'AU Professor Undergraduate');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Avila University', '3', 'AU Professor Graduate');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Avila University', '4', 'AU MBA');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Avila University', '5', 'AU Staff');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Avila University', '6', 'AU Psychology Graduate');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Avila University', '7', 'AU Education Graduate');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Avila University', '8', 'AU Kines Graduate');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Avila University', '9', 'AU VisCom Graduate');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Avila University', '10', 'AU Guest');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Avila University', '11', 'AU Undergraduate Freshman');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Avila University', '12', 'AU Undergraduate Sophmore');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Avila University', '13', 'AU Undergraduate Junior');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Avila University', '14', 'AU Undergraduate Senior');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Avila University', '15', 'AU ILL');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Missouri Western State University', '18', 'MWSU Dual Credit Instructor');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Missouri Western State University', '19', 'MWSU Dual Credit');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Missouri Western State University', '21', 'MWSU Faculty');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Missouri Western State University', '22', 'MWSU Staff');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Missouri Western State University', '23', 'MWSU Students');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Missouri Western State University', '24', 'MWSU Retirees');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Missouri Western State University', '26', 'MWSU Community');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Missouri Western State University', '30', 'MWSU ILL');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Missouri Western State University', '39', 'MWSU Graduate');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Missouri Western State University', '40', 'MWSU Adjunct');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('William Jewell College', '41', 'WJC WJ Student');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('William Jewell College', '43', 'WJC WJ Faculty');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('William Jewell College', '45', 'WJC WJ Staff');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('William Jewell College', '47', 'WJC WJ Alumni');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('William Jewell College', '48', 'WJC WJ College West');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('William Jewell College', '49', 'None');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('William Jewell College', '50', 'WJC WJ Family');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('William Jewell College', '51', 'WJC WJ Community Cards');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('William Jewell College', '52', 'WJC WJ ILL');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('William Jewell College', '54', 'WJC WJ Friend');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Metropolitan Community College', '55', 'MCC Student');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Metropolitan Community College', '56', 'MCC Employee');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Metropolitan Community College', '57', 'MCC ILL');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Metropolitan Community College', '58', 'MCC Non-MOBIUS');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Midwestern Baptist Theological Seminary', '61', 'MBTS Faculty');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Midwestern Baptist Theological Seminary', '62', 'MBTS Adjunct Faculty');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Midwestern Baptist Theological Seminary', '63', 'MBTS Administration');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Midwestern Baptist Theological Seminary', '64', 'None');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Midwestern Baptist Theological Seminary', '65', 'None');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Midwestern Baptist Theological Seminary', '66', 'None');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Midwestern Baptist Theological Seminary', '67', 'MBTS Student');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Midwestern Baptist Theological Seminary', '68', 'MBTS Doctoral Student');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Midwestern Baptist Theological Seminary', '69', 'MBTS Alumni');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Midwestern Baptist Theological Seminary', '70', 'None');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Midwestern Baptist Theological Seminary', '71', 'MBTS Masters Student');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Midwestern Baptist Theological Seminary', '72', 'None');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Midwestern Baptist Theological Seminary', '73', 'None');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Midwestern Baptist Theological Seminary', '74', 'None');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Midwestern Baptist Theological Seminary', '75', 'MBTS Guest');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Midwestern Baptist Theological Seminary', '76', 'MBTS PH.D Student');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Midwestern Baptist Theological Seminary', '77', 'None');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Rockhurst University', '81', 'ROCK RU Student');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Rockhurst University', '82', 'ROCK RU Employee');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Rockhurst University', '83', 'None');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Rockhurst University', '84', 'None');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Rockhurst University', '85', 'ROCK Courtesy Card');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Rockhurst University', '86', 'ROCK RU ILL');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Rockhurst University', '87', 'ROCK RU ACCP Faculty');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Rockhurst University', '88', 'ROCK RU Alumni');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('North Central Missouri College', '90', 'NCMC Student');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('North Central Missouri College', '91', 'None');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('North Central Missouri College', '92', 'NCMC Visiting Student');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('North Central Missouri College', '93', 'NCMC Upward Bound Student');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('North Central Missouri College', '94', 'NCMC Community');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('North Central Missouri College', '95', 'NCMC Staff');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('North Central Missouri College', '96', 'NCMC Administration');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('North Central Missouri College', '97', 'NCMC Faculty');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('North Central Missouri College', '98', 'NCMC College Board');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('North Central Missouri College', '99', 'NCMC Emeritus');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('North Central Missouri College', '100', 'NCMC ILL');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('St. Paul School of Theology', '101', 'SPST Student');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('St. Paul School of Theology', '102', 'None');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('St. Paul School of Theology', '103', 'None');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('St. Paul School of Theology', '104', 'None');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('St. Paul School of Theology', '105', 'None');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('St. Paul School of Theology', '106', 'SPST Faculty/Staff');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('St. Paul School of Theology', '107', 'SPST Adjunct');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('St. Paul School of Theology', '108', 'None');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('St. Paul School of Theology', '109', 'SPST Alumni');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('St. Paul School of Theology', '110', 'None');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('St. Paul School of Theology', '111', 'None');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('St. Paul School of Theology', '112', 'None');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('St. Paul School of Theology', '113', 'None');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('St. Paul School of Theology', '114', 'None');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('St. Paul School of Theology', '115', 'None');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('St. Paul School of Theology', '116', 'None');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('St. Paul School of Theology', '117', 'None');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('St. Paul School of Theology', '118', 'None');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('St. Paul School of Theology', '119', 'None');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('St. Paul School of Theology', '120', 'SPST Courtesy Card');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Conception Abbey', '121', 'CNCPT Students');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Conception Abbey', '122', 'CNCPT Monastic Faculty');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Conception Abbey', '123', 'CNCPT Non-Monastic Faculty');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Conception Abbey', '124', 'CNCPT Non-Faculty Monks');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Conception Abbey', '125', 'CNCPT Staff');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Conception Abbey', '126', 'CNCPT Clyde Sisters');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Conception Abbey', '127', 'CNCPT Community');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Conception Abbey', '128', 'CNCPT ILL');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Conception Abbey', '129', 'CNCPT ILL MOBIUS Non-Returnable');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Conception Abbey', '130', 'CNCPT ILL Non-MOBIUS Non-Returnable');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Kansas City Art Institute', '131', 'KCAI STUDENT');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Kansas City Art Institute', '132', 'KCAI FACULTY FULL-TIME');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Kansas City Art Institute', '133', 'KCAI STAFF');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Kansas City Art Institute', '134', 'KCAI GUEST');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Kansas City Art Institute', '135', 'KCAI FACULTY-PART TIME');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Kansas City Art Institute', '136', 'KCAI VISITING ARTIST');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Kansas City Art Institute', '137', 'None');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Kansas City Art Institute', '138', 'None');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Kansas City Art Institute', '139', 'None');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Kansas City Art Institute', '140', 'KCAI RETIRED');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Kansas City Art Institute', '141', 'KCAI INTERLIBRARY LOAN');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Kansas City Art Institute', '142', 'KCAI Student Restricted');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Kansas City Art Institute', '143', 'None');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Kansas City Art Institute', '144', 'KCAI Library Staff');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Park University', '151', 'PARK Student');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Park University', '152', 'PARK Faculty');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Park University', '153', 'PARK Staff');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Park University', '154', 'PARK Community');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Park University', '155', 'PARK Courtesy');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Park University', '156', 'PARK ILL');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Park University', '157', 'PARK Alumni');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Park University', '158', 'PARK Emeriti');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Nazarene Theological Seminary', '160', 'NTS Student');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Nazarene Theological Seminary', '161', 'NTS Faculty');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Nazarene Theological Seminary', '162', 'NTS DMin');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Nazarene Theological Seminary', '163', 'NTS Courtesy');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Nazarene Theological Seminary', '164', 'NTS ILL');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Nazarene Theological Seminary', '165', 'NTS Community');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Nazarene Theological Seminary', '166', 'NTS Alumni');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Nazarene Theological Seminary', '167', 'NTS Praxis');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Kansas City University', '170', 'KCU Students');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Kansas City University', '171', 'KCU Faculty');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Kansas City University', '172', 'KCU Staff');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Kansas City University', '173', 'KCU ILL');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Kansas City University', '174', 'KCU Special');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Kansas City University', '175', 'KCU Residents');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Kansas City University', '176', 'KCU Joplin Students');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Kansas City University', '177', 'KCU Joplin Faculty');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Kansas City University', '178', 'KCU Joplin Staff');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Kansas City University', '179', 'KCU Joplin Residents');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Northwest Missouri State University', '180', 'NWMSU NW Undergraduate Student');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Northwest Missouri State University', '181', 'NWMSU Graduate Student');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Northwest Missouri State University', '183', 'NWMSU NW Staff');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Northwest Missouri State University', '184', 'NWMSU Faculty');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Northwest Missouri State University', '185', 'NWMSU Alumni');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Northwest Missouri State University', '186', 'NWMSU NWM Family');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Northwest Missouri State University', '187', 'NWMSU Maryville Public Library');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Northwest Missouri State University', '188', 'NWMSU Special Borrower');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Northwest Missouri State University', '189', 'NWMSU ILL');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Northwest Missouri State University', '190', 'NWMSU Student');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Northwest Missouri State University', '192', 'NWMSU Other');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Northwest Missouri State University', '194', 'NWMSU Retiree');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Kansas City KS Community College', '261', 'KCKCC Employee');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Kansas City KS Community College', '262', 'KCKCC Student');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Kansas City KS Community College', '263', 'KCKCC Community');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Kansas City KS Community College', '264', 'KCKCC Alumni');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Benedictine College', '271', 'BC Student');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Benedictine College', '272', 'BC Faculty');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Benedictine College', '273', 'BC Staff');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Benedictine College', '274', 'BC Monastic');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Benedictine College', '275', 'BC Public');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Benedictine College', '276', 'BC ILL');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Calvary University', '281', 'CU Faculty/Staff');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Calvary University', '282', 'CU Guest/Alumni');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Calvary University', '283', 'CU Student');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Crowder College', '1', 'CROW Student');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Crowder College', '2', 'CROW Faculty');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Crowder College', '3', 'CROW Staff');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Crowder College', '4', 'CROW Guest');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Crowder College', '5', 'CROW ILL');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Crowder College', '6', 'CROW Booking Test');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Drury University', '26', 'DU Student');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Drury University', '27', 'DU Alumni');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Drury University', '28', 'DU Faculty');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Drury University', '29', 'DU Staff');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Drury University', '32', 'DU Other');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Drury University', '33', 'DU Adjunct');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Missouri Southern State University', '51', 'MSSU Undergraduate');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Missouri Southern State University', '52', 'MSSU Faculty');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Missouri Southern State University', '53', 'MSSU Staff');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Missouri Southern State University', '54', 'MSSU Community');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Missouri Southern State University', '55', 'MSSU ILL');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Missouri Southern State University', '56', 'MSSU VIPS');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Missouri Southern State University', '57', 'MSSU Area Students');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Missouri Southern State University', '58', 'None');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Missouri Southern State University', '59', 'None');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Missouri Southern State University', '60', 'None');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Missouri Southern State University', '61', 'None');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Missouri Southern State University', '62', 'MSSU In-House');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Missouri Southern State University', '63', 'MSSU Graduate Student');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Missouri Southern State University', '64', 'MSSU Friend');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Ozarks Technical Community College', '76', 'OTC Student');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Ozarks Technical Community College', '77', 'OTC Faculty-Staff');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Ozarks Technical Community College', '78', 'None');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Ozarks Technical Community College', '79', 'OTC Community');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Ozarks Technical Community College', '80', 'None');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Ozarks Technical Community College', '81', 'None');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Southwest Baptist University', '101', 'SBU Undergraduate');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Southwest Baptist University', '102', 'SBU Graduate');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Southwest Baptist University', '103', 'SBU Faculty Full Time');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Southwest Baptist University', '104', 'SBU Faculty Retired');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Southwest Baptist University', '105', 'None');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Southwest Baptist University', '106', 'None');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Southwest Baptist University', '107', 'SBU Staff');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Southwest Baptist University', '108', 'SBU Guest Adult');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Southwest Baptist University', '109', 'None');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Southwest Baptist University', '110', 'SBU ILL');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Southwest Baptist University', '111', 'None');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Southwest Baptist University', '112', 'None');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Southwest Baptist University', '113', 'None');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Southwest Baptist University', '114', 'SBU Student Correspondence');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Southwest Baptist University', '115', 'None');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Southwest Baptist University', '116', 'None');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Cottey College', '150', 'COTT Admin');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Cottey College', '151', 'COTT Alumnae');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Cottey College', '152', 'COTT Emeritus Faculty');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Cottey College', '153', 'COTT Retired Staff');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Cottey College', '154', 'COTT Faculty');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Cottey College', '155', 'COTT Family');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Cottey College', '156', 'COTT 1st Year');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Cottey College', '157', 'COTT ILL');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Cottey College', '158', 'COTT PEO');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Cottey College', '159', 'COTT 2nd Year');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Cottey College', '160', 'COTT Staff');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Cottey College', '162', 'COTT Public');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Cottey College', '163', 'COTT Nevada R-V Teacher');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Cottey College', '164', 'COTT 3rd Year');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Cottey College', '165', 'COTT 4th Year');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Evangel University', '170', 'EU Masters Student');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Evangel University', '171', 'EU Faculty & Administration');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Evangel University', '172', 'EU Staff');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Evangel University', '173', 'EU Adjunct Faculty');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Evangel University', '174', 'EU Alumni');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Evangel University', '175', 'None');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Evangel University', '176', 'EU Doctoral Student');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Evangel University', '177', 'EU ILL');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Evangel University', '178', 'EU Guest');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Evangel University', '179', 'EU Classroom Assignment');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Evangel University', '180', 'None');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Evangel University', '181', 'EU Undergraduate Student');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Evangel University', '182', 'EU Reciprocal Borrower');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Evangel University', '183', 'EU Global Faculty');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Evangel University', '184', 'EU Temp');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Ozark Christian College', '185', 'OCC Residential');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Ozark Christian College', '186', 'None');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Ozark Christian College', '187', 'OCC Faculty');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Ozark Christian College', '188', 'OCC Staff');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Ozark Christian College', '189', 'OCC Affiliates');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Ozark Christian College', '190', 'OCC Graduate');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Ozark Christian College', '191', 'None');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Ozark Christian College', '192', 'None');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Ozark Christian College', '193', 'OCC Online');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Ozark Christian College', '194', 'OCC Alumni');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Southwestern Baptist Theological Seminary', '1', 'SWBTS Student');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Southwestern Baptist Theological Seminary', '2', 'SWBTS Doctoral Student');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Southwestern Baptist Theological Seminary', '3', 'None');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Southwestern Baptist Theological Seminary', '4', 'SWBTS ATLA/ACL Reciprocal');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Southwestern Baptist Theological Seminary', '5', 'SWBTS Texshare');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Southwestern Baptist Theological Seminary', '6', 'SWBTS Guest/Family Member');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Southwestern Baptist Theological Seminary', '7', 'None');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Southwestern Baptist Theological Seminary', '8', 'SWBTS Alumni');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Southwestern Baptist Theological Seminary', '9', 'SWBTS VIP');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Southwestern Baptist Theological Seminary', '10', 'SWBTS Faculty');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Southwestern Baptist Theological Seminary', '11', 'SWBTS Adjunct Family');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Southwestern Baptist Theological Seminary', '12', 'SWBTS Staff');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Southwestern Baptist Theological Seminary', '13', 'None');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Southwestern Baptist Theological Seminary', '14', 'SWBTS Librarians');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Southwestern Baptist Theological Seminary', '15', 'SWBTS ILL');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Southwestern Baptist Theological Seminary', '16', 'None');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Southwestern Baptist Theological Seminary', '17', 'None');
INSERT INTO patron_import.ptype_mapping("name", "ptype", "foliogroup") VALUES ('Southwestern Baptist Theological Seminary', '18', 'SWBTS Emeritus');
