insert into patron_import.institution_map (id, cluster, institution, folder_path, file, file_pattern, module, esid)
values  (1, 'archway', 'East Central College', '/mnt/dropbox/archway/home/archway/incoming', 'eccpat.txt', 'eccpat', 'GenericParser', 'barcode'),
        (2, 'archway', 'Jefferson College', '/mnt/dropbox/archway/home/archway/incoming', 'jcpat.txt', 'jcpat', 'GenericParser', ''),
        (3, 'archway', 'Mineral Area College', '/mnt/dropbox/archway/home/archway/incoming', 'MACStummddyy.txt', 'MACStu', 'GenericParser', ''),
        (4, 'archway', 'Mineral Area College', '/mnt/dropbox/archway/home/archway/incoming', 'MACStaffmmddyy.txt', 'MACStaff', 'GenericParser', ''),
        (5, 'archway', 'Mineral Area College', '/mnt/dropbox/archway/home/archway/incoming', 'MACAdjunctmmddyy.txt', 'MACAdjunct', 'GenericParser', ''),
        (6, 'archway', 'St. Charles Community College', '/mnt/dropbox/archway/home/archway/incoming', 'SCCstudent', 'SCCstudent', 'GenericParser', 'email'),
        (7, 'archway', 'St. Charles Community College', '/mnt/dropbox/archway/home/archway/incoming', 'SCCstaff', 'SCCstaff', 'GenericParser', 'email'),
        (8, 'archway', 'St. Louis Community College', '/mnt/dropbox/archway/home/archway/incoming', 'SLCCStudent', 'SLCCStudent', 'GenericParser', ''),
        (9, 'archway', 'St. Louis Community College', '/mnt/dropbox/archway/home/archway/incoming', 'SLCCStaff', 'SLCCStaff', 'GenericParser', ''),
        (10, 'archway', 'Three Rivers College', '/mnt/dropbox/archway/home/archway/incoming', 'TRCstuyyyymmdd', 'TRCstu', 'GenericParser', 'barcode'),
        (11, 'archway', 'Three Rivers College', '/mnt/dropbox/archway/home/archway/incoming', 'TRCstaffyyyymmdd', 'TRCstaff', 'GenericParser', 'barcode'),
        (12, 'archway', 'University of Health Sciences & Pharmacy', '/mnt/dropbox/archway/home/archway/incoming', 'stlcoppat.txt', 'stlcoppat', 'GenericParser', ''),
        (13, 'arthur', 'Columbia College', '/mnt/dropbox/arthur/home/arthur/incoming', 'COLUMBIA_PATRONS', 'COLUMBIA_PATRONS', 'GenericParser', 'barcode'),
        (14, 'arthur', 'Lincoln University', '/mnt/dropbox/arthur/home/arthur/incoming', 'LUPAT.Dyymdd', 'LUPAT.D', 'GenericParser', 'email'),
        (15, 'arthur', 'Missouri State Library', '/mnt/dropbox/arthur/home/arthur/incoming', 'n/a', 'n/a', 'GenericParser', 'barcode'),
        (16, 'arthur', 'Stephens College', '/mnt/dropbox/arthur/home/arthur/incoming', 'scstudent', 'scstudent', 'GenericParser', 'email'),
        (17, 'arthur', 'Westminster College', '/mnt/dropbox/arthur/home/arthur/incoming', 'wcstudents.txt', 'wcstudents', 'GenericParser', 'email'),
        (18, 'arthur', 'William Woods University', '/mnt/dropbox/arthur/home/arthur/incoming', 'WWUpatrons.txt', 'WWUpatrons', 'GenericParser', 'email'),
        (19, 'arthur', 'William Woods University', '/mnt/dropbox/arthur/home/arthur/incoming', 'WWUbarcodesUG.txt', 'WWUbarcodesUG', 'GenericParser', 'email'),
        (20, 'avalon', 'A.T. Still University', '/mnt/dropbox/avalon/home/avalon/incoming', 'ATSU_mmddyyyy.txt', 'ATSU_', 'GenericParser', 'email'),
        (21, 'avalon', 'Central Methodist University', '/mnt/dropbox/avalon/home/avalon/incoming', 'CMUstuyyyymmdd.out', 'CMUstu', 'GenericParser', ''),
        (22, 'avalon', 'Central Methodist University', '/mnt/dropbox/avalon/home/avalon/incoming', 'CMUgryyyymmdd.out', 'CMUgr', 'GenericParser', ''),
        (23, 'avalon', 'Central Methodist University', '/mnt/dropbox/avalon/home/avalon/incoming', 'CMUfacyyyymmdd.out', 'CMUfac', 'GenericParser', ''),
        (24, 'avalon', 'Culver-Stockton College', '/mnt/dropbox/avalon/home/avalon/incoming', 'csctmmddyyyy.txt', 'csct', 'GenericParser', 'email'),
        (25, 'avalon', 'Hannibal-LaGrange University', '/mnt/dropbox/avalon/home/avalon/incoming', 'HLG-STUDENTS', 'HLG-STUDENTS', 'GenericParser', 'email'),
        (26, 'avalon', 'Missouri Valley College', '/mnt/dropbox/avalon/home/avalon/incoming', 'MVC_Student_Updates', 'MVC_Student_Updates', 'GenericParser', 'email'),
        (27, 'avalon', 'Moberly Area Community College', '/mnt/dropbox/avalon/home/avalon/incoming', 'MACCPatLoadmm-dd-yy', 'MACCPatLoad', 'GenericParser', ''),
        (28, 'avalon', 'State Fair Community College', '/mnt/dropbox/avalon/home/avalon/incoming', 'SFCC_Student_mmddyy.txt', 'SFCC_Student_', 'GenericParser', ''),
        (29, 'avalon', 'State Fair Community College', '/mnt/dropbox/avalon/home/avalon/incoming', 'SFCC_Staff_mmddyy.txt', 'SFCC_Staff_', 'GenericParser', ''),
        (30, 'avalon', 'State Technical College', '/mnt/dropbox/avalon/home/avalon/incoming', 'STC_yyyy-mm-dd', 'STC_', 'GenericParser', ''),
        (31, 'avalon', 'Truman State University', '/mnt/dropbox/avalon/home/avalon/incoming', 'tpbstupat', 'tpbstupat', 'GenericParser', 'barcode'),
        (32, 'bridges', 'Concordia Seminary', '/mnt/dropbox/bridges/home/bridges/incoming', 'cslpatrons.txt', 'cslpatrons', 'GenericParser', ''),
        (33, 'bridges', 'Covenant Seminary', '/mnt/dropbox/bridges/home/bridges/incoming', 'covstu.txt', 'covstu', 'GenericParser', ''),
        (34, 'bridges', 'Covenant Seminary', '/mnt/dropbox/bridges/home/bridges/incoming', 'covfac.txt', 'covfac', 'GenericParser', ''),
        (35, 'bridges', 'Fontbonne University', '/mnt/dropbox/bridges/home/bridges/incoming', 'FCstuPAT.DAT', 'FCstuPAT.DAT', 'GenericParser', 'email'),
        (36, 'bridges', 'Fontbonne University', '/mnt/dropbox/bridges/home/bridges/incoming', 'FCfacPAT.DAT', 'FCfacPAT.DAT', 'GenericParser', 'email'),
        (37, 'bridges', 'Harris-Stowe State University', '/mnt/dropbox/bridges/home/bridges/incoming', 'HSSUyymmdd.txt', 'HSSU', 'GenericParser', 'barcode'),
        (38, 'bridges', 'Kenrick-Glennon Seminary', '/mnt/dropbox/bridges/home/bridges/incoming', 'n/a', 'n/a', 'GenericParser', ''),
        (39, 'bridges', 'Lindenwood University', '/mnt/dropbox/bridges/home/bridges/incoming', 'LUSTUPAT.txt', 'LUSTUPAT', 'GenericParser', 'email'),
        (40, 'bridges', 'Lindenwood University', '/mnt/dropbox/bridges/home/bridges/incoming', 'LUFACPAT.txt', 'LUFACPAT', 'GenericParser', 'email'),
        (41, 'bridges', 'Logan University', '/mnt/dropbox/bridges/home/bridges/incoming', 'loganstu.txt', 'loganstu', 'GenericParser', ''),
        (42, 'bridges', 'Maryville University', '/mnt/dropbox/bridges/home/bridges/incoming', 'mustupat.dyymmdd.txt', 'mustupat.d', 'GenericParser', ''),
        (43, 'bridges', 'Maryville University', '/mnt/dropbox/bridges/home/bridges/incoming', 'mustapat.dyymmdd.txt', 'mustapat.d', 'GenericParser', ''),
        (44, 'bridges', 'Maryville University', '/mnt/dropbox/bridges/home/bridges/incoming', 'mufacpat.dyymmdd.txt', 'mufacpat.d', 'GenericParser', ''),
        (45, 'bridges', 'Maryville University', '/mnt/dropbox/bridges/home/bridges/incoming', 'muadjpat.dyymmdd.txt', 'muadjpat.d', 'GenericParser', ''),
        (46, 'bridges', 'Missouri Baptist University', '/mnt/dropbox/bridges/home/bridges/incoming', 'mobapstu.txt', 'mobapstu', 'GenericParser', 'email'),
        (47, 'bridges', 'Webster University-Eden Seminary', '/mnt/dropbox/bridges/home/bridges/incoming', 'EWLPat.txt', 'EWLPat', 'GenericParser', ''),
        (48, 'explore', 'Goldfarb School of Nursing', '/mnt/dropbox/explore/home/explore/incoming', 'n/a', 'n/a', 'GenericParser', ''),
        (49, 'explore', 'Missouri Botanical Garden', '/mnt/dropbox/explore/home/explore/incoming', 'n/a', 'n/a', 'GenericParser', 'email'),
        (50, 'explore', 'Missouri History Museum', '/mnt/dropbox/explore/home/explore/incoming', 'n/a', 'n/a', 'GenericParser', 'barcode'),
        (51, 'explore', 'Saint Louis Art Museum', '/mnt/dropbox/explore/home/explore/incoming', 'n/a', 'n/a', 'GenericParser', ''),
        (52, 'kc-towers', 'Avila University', '/mnt/dropbox/kc-towers/home/kc-towers/incoming', 'AvilaUniversity', 'AvilaUniversity', 'GenericParser', 'barcode'),
        (53, 'kc-towers', 'Benedictine College', '/mnt/dropbox/kc-towers/home/kc-towers/incoming', 'bcpatrons.txt', 'bcpatrons', 'GenericParser', 'email'),
        (54, 'kc-towers', 'Calvary University', '/mnt/dropbox/kc-towers/home/kc-towers/incoming', 'n/a', 'n/a', 'GenericParser', 'barcode'),
        (55, 'kc-towers', 'Conception Abbey', '/mnt/dropbox/kc-towers/home/kc-towers/incoming', 'n/a', 'n/a', 'GenericParser', ''),
        (56, 'kc-towers', 'Kansas City Art Institute', '/mnt/dropbox/kc-towers/home/kc-towers/incoming', 'KCAI', 'KCAI', 'GenericParser', 'barcode'),
        (57, 'kc-towers', 'Kansas City KS Community College', '/mnt/dropbox/kc-towers/home/kc-towers/incoming', 'KCKCC_LIB_STU.txt', 'KCKCC_LIB_STU', 'GenericParser', ''),
        (58, 'kc-towers', 'Kansas City KS Community College', '/mnt/dropbox/kc-towers/home/kc-towers/incoming', 'KCKCC_LIB_EMP.txt', 'KCKCC_LIB_EMP', 'GenericParser', ''),
        (59, 'kc-towers', 'Kansas City University', '/mnt/dropbox/kc-towers/home/kc-towers/incoming', 'KCU-yyyy-mm-dd.txt', 'KCU-', 'GenericParser', 'barcode'),
        (60, 'kc-towers', 'Metropolitan Community College', '/mnt/dropbox/kc-towers/home/kc-towers/incoming', 'mccstuMMYY.txt', 'mccstu', 'GenericParser', ''),
        (61, 'kc-towers', 'Metropolitan Community College', '/mnt/dropbox/kc-towers/home/kc-towers/incoming', 'mccfacMMYY.txt', 'mccfac', 'GenericParser', ''),
        (62, 'kc-towers', 'Midwestern Baptist Theological Seminary', '/mnt/dropbox/kc-towers/home/kc-towers/incoming', 'mbtsstu.dyymmdd.txt', 'mbtsstu.d', 'GenericParser', 'email'),
        (63, 'kc-towers', 'Missouri Western State University', '/mnt/dropbox/kc-towers/home/kc-towers/incoming', 'mwsuugr.txt', 'mwsuugr', 'GenericParser', 'barcode'),
        (64, 'kc-towers', 'Missouri Western State University', '/mnt/dropbox/kc-towers/home/kc-towers/incoming', 'mwsugr.txt', 'mwsugr', 'GenericParser', 'barcode'),
        (65, 'kc-towers', 'Missouri Western State University', '/mnt/dropbox/kc-towers/home/kc-towers/incoming', 'mwsufac.txt', 'mwsufac', 'GenericParser', 'barcode'),
        (66, 'kc-towers', 'Missouri Western State University', '/mnt/dropbox/kc-towers/home/kc-towers/incoming', 'mwsuexp.txt', 'mwsuexp', 'GenericParser', 'barcode'),
        (67, 'kc-towers', 'Missouri Western State University', '/mnt/dropbox/kc-towers/home/kc-towers/incoming', 'mwsuadj.txt', 'mwsuadj', 'GenericParser', 'barcode'),
        (68, 'kc-towers', 'Missouri Western State University', '/mnt/dropbox/kc-towers/home/kc-towers/incoming', 'mwsuinst.txt', 'mwsuinst', 'GenericParser', 'barcode'),
        (69, 'kc-towers', 'Missouri Western State University', '/mnt/dropbox/kc-towers/home/kc-towers/incoming', 'mwsuwdraw.txt', 'mwsuwdraw', 'GenericParser', 'barcode'),
        (70, 'kc-towers', 'Nazarene Theological Seminary', '/mnt/dropbox/kc-towers/home/kc-towers/incoming', 'nts_patrons.txt', 'nts_patrons', 'GenericParser', 'email'),
        (71, 'kc-towers', 'North Central Missouri College', '/mnt/dropbox/kc-towers/home/kc-towers/incoming', 'ncmcstu.txt', 'ncmcstu', 'GenericParser', ''),
        (72, 'kc-towers', 'Northwest Missouri State University', '/mnt/dropbox/kc-towers/home/kc-towers/incoming', 'nwmsustu.txt', 'nwmsustu', 'GenericParser', ''),
        (73, 'kc-towers', 'Northwest Missouri State University', '/mnt/dropbox/kc-towers/home/kc-towers/incoming', 'nwmsuempl.txt', 'nwmsuempl', 'GenericParser', ''),
        (74, 'kc-towers', 'Park University', '/mnt/dropbox/kc-towers/home/kc-towers/incoming', 'parkstufac.txt', 'parkstufac', 'GenericParser', ''),
        (75, 'kc-towers', 'Rockhurst University', '/mnt/dropbox/kc-towers/home/kc-towers/incoming', 'RKRST_Stu_mm-dd-yyyy.txt', 'RKRST_Stu_', 'GenericParser', ''),
        (76, 'kc-towers', 'Rockhurst University', '/mnt/dropbox/kc-towers/home/kc-towers/incoming', 'RKRST_Staff_mm-dd-yyyy.txt', 'RKRST_Staff_', 'GenericParser', ''),
        (77, 'kc-towers', 'Rockhurst University', '/mnt/dropbox/kc-towers/home/kc-towers/incoming', 'RKRST_Faculty_mm-dd-yyyy.txt', 'RKRST_Faculty_', 'GenericParser', ''),
        (78, 'kc-towers', 'Saint Paul School of Theology', '/mnt/dropbox/kc-towers/home/kc-towers/incoming', 'n/a', 'n/a', 'GenericParser', 'email'),
        (79, 'kc-towers', 'William Jewell College', '/mnt/dropbox/kc-towers/home/kc-towers/incoming', 'WJC_MOBIUS_STUDENTS.txt', 'WJC_MOBIUS_STUDENTS', 'GenericParser', ''),
        (80, 'swan', 'Cottey College', '/mnt/dropbox/swan/home/swan/incoming', 'COTTyyyymmdd.txt', 'COTT', 'GenericParser', 'barcode'),
        (81, 'swan', 'Crowder College', '/mnt/dropbox/swan/home/swan/incoming', 'ccstupat.txt', 'ccstupat', 'GenericParser', 'email'),
        (82, 'swan', 'Drury University', '/mnt/dropbox/swan/home/swan/incoming', 'DRURYPAT_students.txt', 'DRURYPAT_students', 'GenericParser', 'barcode'),
        (83, 'swan', 'Drury University', '/mnt/dropbox/swan/home/swan/incoming', 'DRURYPAT_employees.txt', 'DRURYPAT_employees', 'GenericParser', 'barcode'),
        (84, 'swan', 'Drury University', '/mnt/dropbox/swan/home/swan/incoming', 'DRURYPAT_alumni.txt', 'DRURYPAT_alumni', 'GenericParser', 'barcode'),
        (85, 'swan', 'Evangel University', '/mnt/dropbox/swan/home/swan/incoming', 'EUPatronCamsExport_month_day_year', 'EUPatronCamsExport_', 'GenericParser', 'email'),
        (86, 'swan', 'Missouri Southern State University', '/mnt/dropbox/swan/home/swan/incoming', 'MSSCALL', 'MSSCALL', 'GenericParser', ''),
        (87, 'swan', 'Ozark Christian College', '/mnt/dropbox/swan/home/swan/incoming', 'MobiusUploadyyyydd.txt', 'MobiusUpload', 'GenericParser', 'barcode'),
        (88, 'swan', 'Ozarks Technical Community College', '/mnt/dropbox/swan/home/swan/incoming', 'otcpat.txt', 'otcpat', 'GenericParser', 'email'),
        (89, 'swan', 'Southwest Baptist University', '/mnt/dropbox/swan/home/swan/incoming', 'SBUPATRONS', 'SBUPATRONS', 'GenericParser', 'email'),
        (90, 'swbts', 'Southwestern Baptist Theological Seminary', '/mnt/dropbox/swbts/home/swbts/incoming', 'patronLoad.marc', 'patronLoad', 'GenericParser', '');